/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package ar.uba.fi.tppro.core.service.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class MessageId implements org.apache.thrift.TBase<MessageId, MessageId._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("MessageId");

  private static final org.apache.thrift.protocol.TField PREVIOUS_STATE_FIELD_DESC = new org.apache.thrift.protocol.TField("previousState", org.apache.thrift.protocol.TType.I64, (short)1);
  private static final org.apache.thrift.protocol.TField NEXT_STATE_FIELD_DESC = new org.apache.thrift.protocol.TField("nextState", org.apache.thrift.protocol.TType.I64, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new MessageIdStandardSchemeFactory());
    schemes.put(TupleScheme.class, new MessageIdTupleSchemeFactory());
  }

  public long previousState; // required
  public long nextState; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    PREVIOUS_STATE((short)1, "previousState"),
    NEXT_STATE((short)2, "nextState");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // PREVIOUS_STATE
          return PREVIOUS_STATE;
        case 2: // NEXT_STATE
          return NEXT_STATE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __PREVIOUSSTATE_ISSET_ID = 0;
  private static final int __NEXTSTATE_ISSET_ID = 1;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.PREVIOUS_STATE, new org.apache.thrift.meta_data.FieldMetaData("previousState", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.NEXT_STATE, new org.apache.thrift.meta_data.FieldMetaData("nextState", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(MessageId.class, metaDataMap);
  }

  public MessageId() {
  }

  public MessageId(
    long previousState,
    long nextState)
  {
    this();
    this.previousState = previousState;
    setPreviousStateIsSet(true);
    this.nextState = nextState;
    setNextStateIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public MessageId(MessageId other) {
    __isset_bitfield = other.__isset_bitfield;
    this.previousState = other.previousState;
    this.nextState = other.nextState;
  }

  public MessageId deepCopy() {
    return new MessageId(this);
  }

  @Override
  public void clear() {
    setPreviousStateIsSet(false);
    this.previousState = 0;
    setNextStateIsSet(false);
    this.nextState = 0;
  }

  public long getPreviousState() {
    return this.previousState;
  }

  public MessageId setPreviousState(long previousState) {
    this.previousState = previousState;
    setPreviousStateIsSet(true);
    return this;
  }

  public void unsetPreviousState() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __PREVIOUSSTATE_ISSET_ID);
  }

  /** Returns true if field previousState is set (has been assigned a value) and false otherwise */
  public boolean isSetPreviousState() {
    return EncodingUtils.testBit(__isset_bitfield, __PREVIOUSSTATE_ISSET_ID);
  }

  public void setPreviousStateIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __PREVIOUSSTATE_ISSET_ID, value);
  }

  public long getNextState() {
    return this.nextState;
  }

  public MessageId setNextState(long nextState) {
    this.nextState = nextState;
    setNextStateIsSet(true);
    return this;
  }

  public void unsetNextState() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __NEXTSTATE_ISSET_ID);
  }

  /** Returns true if field nextState is set (has been assigned a value) and false otherwise */
  public boolean isSetNextState() {
    return EncodingUtils.testBit(__isset_bitfield, __NEXTSTATE_ISSET_ID);
  }

  public void setNextStateIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __NEXTSTATE_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case PREVIOUS_STATE:
      if (value == null) {
        unsetPreviousState();
      } else {
        setPreviousState((Long)value);
      }
      break;

    case NEXT_STATE:
      if (value == null) {
        unsetNextState();
      } else {
        setNextState((Long)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case PREVIOUS_STATE:
      return Long.valueOf(getPreviousState());

    case NEXT_STATE:
      return Long.valueOf(getNextState());

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case PREVIOUS_STATE:
      return isSetPreviousState();
    case NEXT_STATE:
      return isSetNextState();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof MessageId)
      return this.equals((MessageId)that);
    return false;
  }

  public boolean equals(MessageId that) {
    if (that == null)
      return false;

    boolean this_present_previousState = true;
    boolean that_present_previousState = true;
    if (this_present_previousState || that_present_previousState) {
      if (!(this_present_previousState && that_present_previousState))
        return false;
      if (this.previousState != that.previousState)
        return false;
    }

    boolean this_present_nextState = true;
    boolean that_present_nextState = true;
    if (this_present_nextState || that_present_nextState) {
      if (!(this_present_nextState && that_present_nextState))
        return false;
      if (this.nextState != that.nextState)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(MessageId other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    MessageId typedOther = (MessageId)other;

    lastComparison = Boolean.valueOf(isSetPreviousState()).compareTo(typedOther.isSetPreviousState());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPreviousState()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.previousState, typedOther.previousState);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetNextState()).compareTo(typedOther.isSetNextState());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetNextState()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.nextState, typedOther.nextState);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("MessageId(");
    boolean first = true;

    sb.append("previousState:");
    sb.append(this.previousState);
    first = false;
    if (!first) sb.append(", ");
    sb.append("nextState:");
    sb.append(this.nextState);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class MessageIdStandardSchemeFactory implements SchemeFactory {
    public MessageIdStandardScheme getScheme() {
      return new MessageIdStandardScheme();
    }
  }

  private static class MessageIdStandardScheme extends StandardScheme<MessageId> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, MessageId struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // PREVIOUS_STATE
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.previousState = iprot.readI64();
              struct.setPreviousStateIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // NEXT_STATE
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.nextState = iprot.readI64();
              struct.setNextStateIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, MessageId struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(PREVIOUS_STATE_FIELD_DESC);
      oprot.writeI64(struct.previousState);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(NEXT_STATE_FIELD_DESC);
      oprot.writeI64(struct.nextState);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class MessageIdTupleSchemeFactory implements SchemeFactory {
    public MessageIdTupleScheme getScheme() {
      return new MessageIdTupleScheme();
    }
  }

  private static class MessageIdTupleScheme extends TupleScheme<MessageId> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, MessageId struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetPreviousState()) {
        optionals.set(0);
      }
      if (struct.isSetNextState()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetPreviousState()) {
        oprot.writeI64(struct.previousState);
      }
      if (struct.isSetNextState()) {
        oprot.writeI64(struct.nextState);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, MessageId struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.previousState = iprot.readI64();
        struct.setPreviousStateIsSet(true);
      }
      if (incoming.get(1)) {
        struct.nextState = iprot.readI64();
        struct.setNextStateIsSet(true);
      }
    }
  }

}

